import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"

import Header from "../components/Header"
import { ThemeProvider } from "../components/theme-provider"
import { ModeToggle } from "../components/dark-mode"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex justify-end p-3">
            <ModeToggle />
          </div>
          <div className="px-16 pt-8">
            <Header />
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
